# Generated by Django 5.2.7 on 2025-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location_url', models.URLField(choices=[('Andijan', 'Andijan'), ('Bukhara', 'Bukhara'), ('Samarkand', 'Samarkand'), ('Tashkent', 'Tashkent'), ('Fergana', 'Fergana')], max_length=2000)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
